### ISSUE TITLE
max()

### ISSUE THREAD

**Issue by Chinees-zhang** [bennyguo/sketch2model#1]
<img width="978" alt="53" src="https://user-images.githubusercontent.com/95740471/170466272-a43ddb28-70f0-46fd-b244-101926363c5f.png">

您好！
如图，请问这个错误是设么原因，麻烦给一下处理的思路。
感谢~

**Comment by mathyouf** [comment]
`/checkpoints/{文件名}.pth`

`python test.py --name 文件名 ...`

**Comment by Chinees-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在正忙，无法亲自回复您的邮件。我将在抽时间，尽快给您回复。

**Comment by bennyguo** [comment]
您好！请确认您以Bench为name进行了训练。
