### ISSUE TITLE
Question about canny edge detector you used.

### ISSUE THREAD

**Issue by Walterkd** [bennyguo/sketch2model#5]
I wanna know what type of canny edge detector did you use? I can not reproduce the effects. Thank you.

**Comment by bennyguo** [comment]
Hi, sorry for the late reply.

When making the ShapeNet-Synthetic dataset, we first perform 9x9 Gaussian blur to the RGB image, then apply canny edge detection using opencv:
```python
sk = cv2.GaussianBlur(im, (9, 9), 0)
sk = cv2.Canny(sk, 50, 150)
```
After this we copy the alpha channel of the color image to the sketch and save the sketch as RGBA.
